// <auto-generated />
using System;
using CareerPath.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerPath.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306160432_SmallchangestoTheDataTypes")]
    partial class SmallchangestoTheDataTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerPath.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("state")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer")
                        .HasColumnName("resources_id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("ResourcesId")
                        .HasDatabaseName("ix_articles_resources_id");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Career", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageSalary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("average_salary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DemandLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("demand_level");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("experience_level");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("FieldIcon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_icon");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("growth_rate");

                    b.Property<string>("JobOpenings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_openings");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("SubField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sub_field");

                    b.Property<string>("TypicalDegree")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typical_degree");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id")
                        .HasName("pk_career");

                    b.ToTable("career", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.CareerPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("career");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<double>("MatchPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("match_percentage");

                    b.Property<int>("StudentAnalysisResultId")
                        .HasColumnType("integer")
                        .HasColumnName("student_analysis_result_id");

                    b.HasKey("Id")
                        .HasName("pk_career_predictions");

                    b.HasIndex("StudentAnalysisResultId")
                        .HasDatabaseName("ix_career_predictions_student_analysis_result_id");

                    b.ToTable("career_predictions", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.CareerProgressionSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("YearsRange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("years_range");

                    b.HasKey("Id")
                        .HasName("pk_career_progression_steps");

                    b.HasIndex("CareerId")
                        .HasDatabaseName("ix_career_progression_steps_career_id");

                    b.ToTable("career_progression_steps", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.CareerRequiredSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("LevelLabel")
                        .HasColumnType("text")
                        .HasColumnName("level_label");

                    b.Property<string>("SkillName")
                        .HasColumnType("text")
                        .HasColumnName("skill_name");

                    b.HasKey("Id")
                        .HasName("pk_career_required_skills");

                    b.HasIndex("CareerId")
                        .HasDatabaseName("ix_career_required_skills_career_id");

                    b.ToTable("career_required_skills", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.CareerResponsibilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibility");

                    b.HasKey("Id")
                        .HasName("pk_career_responsibilities");

                    b.HasIndex("CareerId")
                        .HasDatabaseName("ix_career_responsibilities_career_id");

                    b.ToTable("career_responsibilities", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.CareerTopCompanies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.HasKey("Id")
                        .HasName("pk_career_top_companies");

                    b.HasIndex("CareerId")
                        .HasDatabaseName("ix_career_top_companies_career_id");

                    b.ToTable("career_top_companies", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.ConfidenceScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AnalyticalSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("analytical_skills");

                    b.Property<double?>("CodingSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("coding_skills");

                    b.Property<double?>("CommunicationSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("communication_skills");

                    b.Property<int>("FeatureVectorId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_vector_id");

                    b.Property<double?>("Gpa")
                        .HasColumnType("double precision")
                        .HasColumnName("gpa");

                    b.Property<double?>("NetworkingSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("networking_skills");

                    b.Property<double?>("PresentationSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("presentation_skills");

                    b.Property<double?>("ProblemSolvingSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("problem_solving_skills");

                    b.Property<double?>("TeamworkSkills")
                        .HasColumnType("double precision")
                        .HasColumnName("teamwork_skills");

                    b.HasKey("Id")
                        .HasName("pk_confidence_scores");

                    b.HasIndex("FeatureVectorId")
                        .IsUnique()
                        .HasDatabaseName("ix_confidence_scores_feature_vector_id");

                    b.ToTable("confidence_scores", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer")
                        .HasColumnName("resources_id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("ResourcesId")
                        .HasDatabaseName("ix_courses_resources_id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.FeatureVector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalyticalSkills")
                        .HasColumnType("integer")
                        .HasColumnName("analytical_skills");

                    b.Property<string>("CareerIntent")
                        .HasColumnType("text")
                        .HasColumnName("career_intent");

                    b.Property<int>("CodingSkills")
                        .HasColumnType("integer")
                        .HasColumnName("coding_skills");

                    b.Property<int>("CommunicationSkills")
                        .HasColumnType("integer")
                        .HasColumnName("communication_skills");

                    b.Property<int>("ExtracurricularActivities")
                        .HasColumnType("integer")
                        .HasColumnName("extracurricular_activities");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<int>("FieldSpecificCourses")
                        .HasColumnType("integer")
                        .HasColumnName("field_specific_courses");

                    b.Property<double>("Gpa")
                        .HasColumnType("double precision")
                        .HasColumnName("gpa");

                    b.Property<int>("Internships")
                        .HasColumnType("integer")
                        .HasColumnName("internships");

                    b.Property<int>("LeadershipPositions")
                        .HasColumnType("integer")
                        .HasColumnName("leadership_positions");

                    b.Property<int>("NetworkingSkills")
                        .HasColumnType("integer")
                        .HasColumnName("networking_skills");

                    b.Property<double?>("OverallProfileConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_profile_confidence");

                    b.Property<int>("PresentationSkills")
                        .HasColumnType("integer")
                        .HasColumnName("presentation_skills");

                    b.Property<int>("ProblemSolvingSkills")
                        .HasColumnType("integer")
                        .HasColumnName("problem_solving_skills");

                    b.Property<int>("Projects")
                        .HasColumnType("integer")
                        .HasColumnName("projects");

                    b.Property<bool>("ResearchExperience")
                        .HasColumnType("boolean")
                        .HasColumnName("research_experience");

                    b.Property<int>("StudentAnalysisResultId")
                        .HasColumnType("integer")
                        .HasColumnName("student_analysis_result_id");

                    b.Property<int>("TeamworkSkills")
                        .HasColumnType("integer")
                        .HasColumnName("teamwork_skills");

                    b.HasKey("Id")
                        .HasName("pk_feature_vectors");

                    b.HasIndex("StudentAnalysisResultId")
                        .IsUnique()
                        .HasDatabaseName("ix_feature_vectors_student_analysis_result_id");

                    b.ToTable("feature_vectors", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("career");

                    b.Property<double>("MatchPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("match_percentage");

                    b.Property<double>("ReadinessScore")
                        .HasColumnType("double precision")
                        .HasColumnName("readiness_score");

                    b.Property<int>("StudentAnalysisResultId")
                        .HasColumnType("integer")
                        .HasColumnName("student_analysis_result_id");

                    b.HasKey("Id")
                        .HasName("pk_gap_analyses");

                    b.HasIndex("StudentAnalysisResultId")
                        .HasDatabaseName("ix_gap_analyses_student_analysis_result_id");

                    b.ToTable("gap_analyses", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Advice")
                        .HasColumnType("text")
                        .HasColumnName("advice");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<double>("Gap")
                        .HasColumnType("double precision")
                        .HasColumnName("gap");

                    b.Property<int>("GapAnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("gap_analysis_id");

                    b.Property<double>("IdealValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ideal_value");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<double>("StudentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("student_value");

                    b.HasKey("Id")
                        .HasName("pk_gap_analysis_gaps");

                    b.HasIndex("GapAnalysisId")
                        .HasDatabaseName("ix_gap_analysis_gaps_gap_analysis_id");

                    b.ToTable("gap_analysis_gaps", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisStrength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feature");

                    b.Property<int>("GapAnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("gap_analysis_id");

                    b.Property<double>("IdealValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ideal_value");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double>("StudentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("student_value");

                    b.HasKey("Id")
                        .HasName("pk_gap_analysis_strengths");

                    b.HasIndex("GapAnalysisId")
                        .HasDatabaseName("ix_gap_analysis_strengths_gap_analysis_id");

                    b.ToTable("gap_analysis_strengths", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeaturesMet")
                        .HasColumnType("integer")
                        .HasColumnName("features_met");

                    b.Property<int>("GapAnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("gap_analysis_id");

                    b.Property<int>("HighPriorityGaps")
                        .HasColumnType("integer")
                        .HasColumnName("high_priority_gaps");

                    b.Property<int>("MediumPriorityGaps")
                        .HasColumnType("integer")
                        .HasColumnName("medium_priority_gaps");

                    b.Property<int>("TotalFeatures")
                        .HasColumnType("integer")
                        .HasColumnName("total_features");

                    b.HasKey("Id")
                        .HasName("pk_gap_analysis_summaries");

                    b.HasIndex("GapAnalysisId")
                        .IsUnique()
                        .HasDatabaseName("ix_gap_analysis_summaries_gap_analysis_id");

                    b.ToTable("gap_analysis_summaries", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.InconsistencyDetected", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FeatureVectorId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_vector_id");

                    b.HasKey("Id")
                        .HasName("pk_inconsistencies");

                    b.HasIndex("FeatureVectorId")
                        .HasDatabaseName("ix_inconsistencies_feature_vector_id");

                    b.ToTable("inconsistencies", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.LearningModules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("LearningPathModelId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_path_model_id");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer")
                        .HasColumnName("resource_id");

                    b.Property<string>("concept")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concept");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("maps_to_gap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("maps_to_gap");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("total_resources")
                        .HasColumnType("integer")
                        .HasColumnName("total_resources");

                    b.HasKey("Id")
                        .HasName("pk_learning_modules");

                    b.HasIndex("LearningPathModelId")
                        .HasDatabaseName("ix_learning_modules_learning_path_model_id");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_learning_modules_resource_id");

                    b.ToTable("learning_modules", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.LearningPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_learning_paths");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_learning_paths_student_profile_id");

                    b.ToTable("learning_paths", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.LearningPathModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LearningPathId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_path_id");

                    b.Property<int>("SummaryId")
                        .HasColumnType("integer")
                        .HasColumnName("summary_id");

                    b.Property<string>("field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("selected_career")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_career");

                    b.Property<int>("total_concepts")
                        .HasColumnType("integer")
                        .HasColumnName("total_concepts");

                    b.HasKey("Id")
                        .HasName("pk_learning_path_models");

                    b.HasIndex("LearningPathId")
                        .IsUnique()
                        .HasDatabaseName("ix_learning_path_models_learning_path_id");

                    b.HasIndex("SummaryId")
                        .IsUnique()
                        .HasDatabaseName("ix_learning_path_models_summary_id");

                    b.ToTable("learning_path_models", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "learning_path");
                });

            modelBuilder.Entity("CareerPath.Models.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer")
                        .HasColumnName("resources_id");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_papers");

                    b.HasIndex("ResourcesId")
                        .HasDatabaseName("ix_papers_resources_id");

                    b.ToTable("papers", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Resources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.SourcesUsed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureVectorId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_vector_id");

                    b.Property<bool>("GitHub")
                        .HasColumnType("boolean")
                        .HasColumnName("git_hub");

                    b.Property<bool>("Questionnaire")
                        .HasColumnType("boolean")
                        .HasColumnName("questionnaire");

                    b.Property<bool>("Resume")
                        .HasColumnType("boolean")
                        .HasColumnName("resume");

                    b.HasKey("Id")
                        .HasName("pk_sources_used");

                    b.HasIndex("FeatureVectorId")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_used_feature_vector_id");

                    b.ToTable("sources_used", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.StudentAnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RecommendedCareer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommended_career");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_student_analysis_results");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_student_analysis_results_student_profile_id");

                    b.ToTable("student_analysis_results", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GitHubUsername")
                        .HasColumnType("text")
                        .HasColumnName("git_hub_username");

                    b.Property<bool>("HasResume")
                        .HasColumnType("boolean")
                        .HasColumnName("has_resume");

                    b.Property<DateTime?>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_student_id");

                    b.ToTable("student_profiles", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("estimated_modules")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_modules");

                    b.Property<int>("high_priority_modules")
                        .HasColumnType("integer")
                        .HasColumnName("high_priority_modules");

                    b.Property<int>("medium_priority_modules")
                        .HasColumnType("integer")
                        .HasColumnName("medium_priority_modules");

                    b.Property<string>("start_with")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_with");

                    b.HasKey("Id")
                        .HasName("pk_summaries");

                    b.ToTable("summaries", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Videos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer")
                        .HasColumnName("resources_id");

                    b.Property<string>("channel")
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("is_fresh")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fresh");

                    b.Property<string>("published_at")
                        .HasColumnType("text")
                        .HasColumnName("published_at");

                    b.Property<string>("source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("thumbnail")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail");

                    b.Property<string>("title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("views")
                        .HasColumnType("integer")
                        .HasColumnName("views");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("ResourcesId")
                        .HasDatabaseName("ix_videos_resources_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("CareerRelated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<int?>("RelatedCareerId")
                        .HasColumnType("integer")
                        .HasColumnName("related_career_id");

                    b.Property<string>("RelatedCareerName")
                        .HasColumnType("text")
                        .HasColumnName("related_career_name");

                    b.Property<string>("RelatedCareerSlug")
                        .HasColumnType("text")
                        .HasColumnName("related_career_slug");

                    b.HasKey("Id")
                        .HasName("pk_career_related");

                    b.HasIndex("CareerId")
                        .HasDatabaseName("ix_career_related_career_id");

                    b.HasIndex("RelatedCareerId")
                        .HasDatabaseName("ix_career_related_related_career_id");

                    b.ToTable("career_related", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CareerPath.Models.Article", b =>
                {
                    b.HasOne("CareerPath.Models.Resources", "Resource")
                        .WithMany("Articles")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articles_resources_resources_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CareerPath.Models.CareerPrediction", b =>
                {
                    b.HasOne("CareerPath.Models.StudentAnalysisResult", "StudentAnalysisResult")
                        .WithMany("CareerPredictions")
                        .HasForeignKey("StudentAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_predictions_student_analysis_results_student_analysi");

                    b.Navigation("StudentAnalysisResult");
                });

            modelBuilder.Entity("CareerPath.Models.CareerProgressionSteps", b =>
                {
                    b.HasOne("CareerPath.Models.Career", "Career")
                        .WithMany("ProgressionSteps")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_progression_steps_career_career_id");

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerPath.Models.CareerRequiredSkills", b =>
                {
                    b.HasOne("CareerPath.Models.Career", "Career")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_required_skills_career_career_id");

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerPath.Models.CareerResponsibilities", b =>
                {
                    b.HasOne("CareerPath.Models.Career", "Career")
                        .WithMany("Responsibilities")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_responsibilities_career_career_id");

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerPath.Models.CareerTopCompanies", b =>
                {
                    b.HasOne("CareerPath.Models.Career", "Career")
                        .WithMany("TopCompanies")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_career_top_companies_career_career_id");

                    b.Navigation("Career");
                });

            modelBuilder.Entity("CareerPath.Models.ConfidenceScores", b =>
                {
                    b.HasOne("CareerPath.Models.FeatureVector", "FeatureVector")
                        .WithOne("ConfidenceScores")
                        .HasForeignKey("CareerPath.Models.ConfidenceScores", "FeatureVectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_confidence_scores_feature_vectors_feature_vector_id");

                    b.Navigation("FeatureVector");
                });

            modelBuilder.Entity("CareerPath.Models.Course", b =>
                {
                    b.HasOne("CareerPath.Models.Resources", "Resource")
                        .WithMany("Courses")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_resources_resources_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CareerPath.Models.FeatureVector", b =>
                {
                    b.HasOne("CareerPath.Models.StudentAnalysisResult", "StudentAnalysisResult")
                        .WithOne("FeatureVector")
                        .HasForeignKey("CareerPath.Models.FeatureVector", "StudentAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feature_vectors_student_analysis_results_student_analysis_r");

                    b.Navigation("StudentAnalysisResult");
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysis", b =>
                {
                    b.HasOne("CareerPath.Models.StudentAnalysisResult", "StudentAnalysisResult")
                        .WithMany("GapAnalyses")
                        .HasForeignKey("StudentAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gap_analyses_student_analysis_results_student_analysis_resu");

                    b.Navigation("StudentAnalysisResult");
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisGap", b =>
                {
                    b.HasOne("CareerPath.Models.GapAnalysis", "GapAnalysis")
                        .WithMany("Gaps")
                        .HasForeignKey("GapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gap_analysis_gaps_gap_analyses_gap_analysis_id");

                    b.Navigation("GapAnalysis");
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisStrength", b =>
                {
                    b.HasOne("CareerPath.Models.GapAnalysis", "GapAnalysis")
                        .WithMany("Strengths")
                        .HasForeignKey("GapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gap_analysis_strengths_gap_analyses_gap_analysis_id");

                    b.Navigation("GapAnalysis");
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysisSummary", b =>
                {
                    b.HasOne("CareerPath.Models.GapAnalysis", "GapAnalysis")
                        .WithOne("Summary")
                        .HasForeignKey("CareerPath.Models.GapAnalysisSummary", "GapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gap_analysis_summaries_gap_analyses_gap_analysis_id");

                    b.Navigation("GapAnalysis");
                });

            modelBuilder.Entity("CareerPath.Models.InconsistencyDetected", b =>
                {
                    b.HasOne("CareerPath.Models.FeatureVector", "FeatureVector")
                        .WithMany("Inconsistencies")
                        .HasForeignKey("FeatureVectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inconsistencies_feature_vectors_feature_vector_id");

                    b.Navigation("FeatureVector");
                });

            modelBuilder.Entity("CareerPath.Models.LearningModules", b =>
                {
                    b.HasOne("CareerPath.Models.LearningPathModel", "LearningPathModel")
                        .WithMany("learning_modules")
                        .HasForeignKey("LearningPathModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_modules_learning_path_models_learning_path_model_id");

                    b.HasOne("CareerPath.Models.Resources", "Resources")
                        .WithOne("LearningModule")
                        .HasForeignKey("CareerPath.Models.LearningModules", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_modules_resources_resource_id");

                    b.Navigation("LearningPathModel");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("CareerPath.Models.LearningPath", b =>
                {
                    b.HasOne("CareerPath.Models.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_paths_student_profiles_student_profile_id");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("CareerPath.Models.LearningPathModel", b =>
                {
                    b.HasOne("CareerPath.Models.LearningPath", "LearningPath")
                        .WithOne("learning_path_model")
                        .HasForeignKey("CareerPath.Models.LearningPathModel", "LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_path_models_learning_paths_learning_path_id");

                    b.HasOne("CareerPath.Models.Summary", "Summary")
                        .WithOne("LearningPathModel")
                        .HasForeignKey("CareerPath.Models.LearningPathModel", "SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_path_models_summaries_summary_id");

                    b.Navigation("LearningPath");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("CareerPath.Models.Paper", b =>
                {
                    b.HasOne("CareerPath.Models.Resources", "Resource")
                        .WithMany("Papers")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_papers_resources_resources_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CareerPath.Models.SourcesUsed", b =>
                {
                    b.HasOne("CareerPath.Models.FeatureVector", "FeatureVector")
                        .WithOne("SourcesUsed")
                        .HasForeignKey("CareerPath.Models.SourcesUsed", "FeatureVectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_used_feature_vectors_feature_vector_id");

                    b.Navigation("FeatureVector");
                });

            modelBuilder.Entity("CareerPath.Models.StudentAnalysisResult", b =>
                {
                    b.HasOne("CareerPath.Models.StudentProfile", "StudentProfile")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_analysis_results_student_profiles_student_profile_id");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("CareerPath.Models.StudentProfile", b =>
                {
                    b.HasOne("CareerPath.Models.ApplicationUser", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("CareerPath.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_application_user_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CareerPath.Models.Videos", b =>
                {
                    b.HasOne("CareerPath.Models.Resources", "Resource")
                        .WithMany("Videos")
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_videos_resources_resources_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("CareerRelated", b =>
                {
                    b.HasOne("CareerPath.Models.Career", "Career")
                        .WithMany("RelatedCareers")
                        .HasForeignKey("CareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_career_related_career_career_id");

                    b.HasOne("CareerPath.Models.Career", "RelatedCareer")
                        .WithMany()
                        .HasForeignKey("RelatedCareerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_career_related_career_related_career_id");

                    b.Navigation("Career");

                    b.Navigation("RelatedCareer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CareerPath.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CareerPath.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("CareerPath.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CareerPath.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("CareerPath.Models.ApplicationUser", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CareerPath.Models.Career", b =>
                {
                    b.Navigation("ProgressionSteps");

                    b.Navigation("RelatedCareers");

                    b.Navigation("RequiredSkills");

                    b.Navigation("Responsibilities");

                    b.Navigation("TopCompanies");
                });

            modelBuilder.Entity("CareerPath.Models.FeatureVector", b =>
                {
                    b.Navigation("ConfidenceScores");

                    b.Navigation("Inconsistencies");

                    b.Navigation("SourcesUsed");
                });

            modelBuilder.Entity("CareerPath.Models.GapAnalysis", b =>
                {
                    b.Navigation("Gaps");

                    b.Navigation("Strengths");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("CareerPath.Models.LearningPath", b =>
                {
                    b.Navigation("learning_path_model");
                });

            modelBuilder.Entity("CareerPath.Models.LearningPathModel", b =>
                {
                    b.Navigation("learning_modules");
                });

            modelBuilder.Entity("CareerPath.Models.Resources", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Courses");

                    b.Navigation("LearningModule");

                    b.Navigation("Papers");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("CareerPath.Models.StudentAnalysisResult", b =>
                {
                    b.Navigation("CareerPredictions");

                    b.Navigation("FeatureVector");

                    b.Navigation("GapAnalyses");
                });

            modelBuilder.Entity("CareerPath.Models.StudentProfile", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("CareerPath.Models.Summary", b =>
                {
                    b.Navigation("LearningPathModel");
                });
#pragma warning restore 612, 618
        }
    }
}
